-- ============================================
-- PRODUCT PERFORMANCE ANALYSIS
-- Objective: Analyze product sales
-- and category performance
-- ============================================
USE northwind;
-- 1. Product revenue and units sold
SELECT p.ProductID, p.ProductName, SUM(od.Quantity) AS UnitsSold,
    ROUND(SUM(od.UnitPrice * od.Quantity * (1 - od.Discount)), 2) AS Revenue
FROM Products p
JOIN OrderDetails od ON p.ProductID = od.ProductID
GROUP BY p.ProductID, p.ProductName
ORDER BY Revenue DESC;


-- 2. Top 5 best-selling products
SELECT p.ProductName, SUM(od.Quantity) AS UnitsSold
FROM Products p
JOIN OrderDetails od ON p.ProductID = od.ProductID
GROUP BY p.ProductName
ORDER BY UnitsSold DESC
LIMIT 5;


-- 3. Revenue generated by each category
SELECT c.CategoryName, ROUND(SUM(od.UnitPrice * od.Quantity * (1 - od.Discount)), 2) AS CategoryRevenue
FROM Categories c
JOIN Products p ON c.CategoryID = p.CategoryID
JOIN OrderDetails od ON p.ProductID = od.ProductID
GROUP BY c.CategoryName
ORDER BY CategoryRevenue DESC;